name: Test

on:
  push:
  pull_request:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "[SETUP] Checkout"
        uses: actions/checkout@v2
      - name: "[SETUP] Node.js 16"
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - name: "[SETUP] Install dependencies"
        run: yarn
      - name: "[TEST] Run tests"
        run: yarn test:report
      - name: "[Test] Report tests"
        if: success() || failure()
        with:
          name: test-results
          path: junit.xml
          fail-on-error: "false"
          reporter: jest-junit
          token: ${{ secrets.GITHUB_TOKEN }}
